version: '3.7'

services:

  proxy:
    container_name: proxy
    image: neilpang/nginx-proxy
    restart: always
    network_mode: bridge
    ports:
    - 80:80
    - 443:443
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/acme:/acmecerts
      - ./proxy/conf.d:/etc/nginx/conf.d
  mysql:
    image: mariadb:10
    network_mode: bridge
    container_name: server-db
    restart: on-failure
    volumes:
    - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwertyuiop


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    network_mode: bridge
    container_name: phpmyadmin
    restart: on-failure
    environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
    volumes:
      - /sessions
    ports:
      - 8181:80
    links:
    - mysql

# Wordpress
  wordpress:
    image: wordpress
    network_mode: bridge
    container_name: wordpress
    restart: on-failure
    volumes:
    - ./wordpress/plugins:/var/www/html/wp-content/plugins/
    - ./wordpress/themes:/var/www/html/wp-content/themes/
    - ./wordpress/web/uploads:/var/www/html/wp-content/uploads/

    environment:
      WORDPRESS_DB_NAME: wordpress-db
      VIRTUAL_HOST: docker.pedrojimenez.info
      ENABLE_ACME: "true"
    depends_on:
    - mysql
    links:
    - mysql
